# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guillaume/centrale/P1RV-fusee

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guillaume/centrale/P1RV-fusee

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/guillaume/centrale/P1RV-fusee/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillaume/centrale/P1RV-fusee/CMakeFiles /home/guillaume/centrale/P1RV-fusee/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillaume/centrale/P1RV-fusee/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named P1RV-fusee-threading

# Build rule for target.
P1RV-fusee-threading: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P1RV-fusee-threading
.PHONY : P1RV-fusee-threading

# fast build rule for target.
P1RV-fusee-threading/fast:
	$(MAKE) -f CMakeFiles/P1RV-fusee-threading.dir/build.make CMakeFiles/P1RV-fusee-threading.dir/build
.PHONY : P1RV-fusee-threading/fast

#=============================================================================
# Target rules for targets named P1RV-fusee-interface

# Build rule for target.
P1RV-fusee-interface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P1RV-fusee-interface
.PHONY : P1RV-fusee-interface

# fast build rule for target.
P1RV-fusee-interface/fast:
	$(MAKE) -f interface/CMakeFiles/P1RV-fusee-interface.dir/build.make interface/CMakeFiles/P1RV-fusee-interface.dir/build
.PHONY : P1RV-fusee-interface/fast

#=============================================================================
# Target rules for targets named P1RV-fusee-simulator

# Build rule for target.
P1RV-fusee-simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P1RV-fusee-simulator
.PHONY : P1RV-fusee-simulator

# fast build rule for target.
P1RV-fusee-simulator/fast:
	$(MAKE) -f simulator/CMakeFiles/P1RV-fusee-simulator.dir/build.make simulator/CMakeFiles/P1RV-fusee-simulator.dir/build
.PHONY : P1RV-fusee-simulator/fast

#=============================================================================
# Target rules for targets named P1RV-fusee-arduino-main

# Build rule for target.
P1RV-fusee-arduino-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P1RV-fusee-arduino-main
.PHONY : P1RV-fusee-arduino-main

# fast build rule for target.
P1RV-fusee-arduino-main/fast:
	$(MAKE) -f simulator/arduino/CMakeFiles/P1RV-fusee-arduino-main.dir/build.make simulator/arduino/CMakeFiles/P1RV-fusee-arduino-main.dir/build
.PHONY : P1RV-fusee-arduino-main/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousSubmit.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousMemCheck.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousConfigure.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalSubmit.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalMemCheck.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalTest.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyUpdate.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyStart.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyMemoryCheck.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyBuild.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalUpdate.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named P1RV-fusee-arduino-layer

# Build rule for target.
P1RV-fusee-arduino-layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P1RV-fusee-arduino-layer
.PHONY : P1RV-fusee-arduino-layer

# fast build rule for target.
P1RV-fusee-arduino-layer/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/P1RV-fusee-arduino-layer.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/P1RV-fusee-arduino-layer.dir/build
.PHONY : P1RV-fusee-arduino-layer/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousBuild.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/Continuous.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/Experimental.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalConfigure.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyTest.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyCoverage.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalCoverage.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyMemCheck.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousStart.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlySubmit.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousCoverage.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/Nightly.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/NightlyConfigure.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalStart.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousTest.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousUpdate.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalBuild.dir/build.make simulator/arduino/my_arduino_layer/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named P1RV-fusee-simulation

# Build rule for target.
P1RV-fusee-simulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P1RV-fusee-simulation
.PHONY : P1RV-fusee-simulation

# fast build rule for target.
P1RV-fusee-simulation/fast:
	$(MAKE) -f simulator/simulation/CMakeFiles/P1RV-fusee-simulation.dir/build.make simulator/simulation/CMakeFiles/P1RV-fusee-simulation.dir/build
.PHONY : P1RV-fusee-simulation/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f tests/CMakeFiles/unit_tests.dir/build.make tests/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

threading.o: threading.cpp.o

.PHONY : threading.o

# target to build an object file
threading.cpp.o:
	$(MAKE) -f CMakeFiles/P1RV-fusee-threading.dir/build.make CMakeFiles/P1RV-fusee-threading.dir/threading.cpp.o
.PHONY : threading.cpp.o

threading.i: threading.cpp.i

.PHONY : threading.i

# target to preprocess a source file
threading.cpp.i:
	$(MAKE) -f CMakeFiles/P1RV-fusee-threading.dir/build.make CMakeFiles/P1RV-fusee-threading.dir/threading.cpp.i
.PHONY : threading.cpp.i

threading.s: threading.cpp.s

.PHONY : threading.s

# target to generate assembly for a file
threading.cpp.s:
	$(MAKE) -f CMakeFiles/P1RV-fusee-threading.dir/build.make CMakeFiles/P1RV-fusee-threading.dir/threading.cpp.s
.PHONY : threading.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... P1RV-fusee-threading"
	@echo "... package_source"
	@echo "... package"
	@echo "... P1RV-fusee-interface"
	@echo "... P1RV-fusee-simulator"
	@echo "... P1RV-fusee-arduino-main"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousConfigure"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalTest"
	@echo "... NightlyUpdate"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyBuild"
	@echo "... ExperimentalUpdate"
	@echo "... P1RV-fusee-arduino-layer"
	@echo "... ContinuousBuild"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyTest"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyMemCheck"
	@echo "... ContinuousStart"
	@echo "... NightlySubmit"
	@echo "... ContinuousCoverage"
	@echo "... Nightly"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalStart"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalBuild"
	@echo "... P1RV-fusee-simulation"
	@echo "... unit_tests"
	@echo "... threading.o"
	@echo "... threading.i"
	@echo "... threading.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

